import type { FileKind, MaterialRefType, SourceFile } from '@/api/types';
import type { FileIconName } from '@/components/ui/FileIcon';

const KIND_ICON: Record<FileKind, FileIconName> = {
  audio: 'audio',
  doc: 'ms-word',
  image: 'image',
  json: 'json',
  md: 'markdown',
  pdf: 'pdf',
  sheet: 'ms-excel',
  slides: 'ms-powerpoint',
  txt: 'text',
  unknown: '_file',
};

// The backend files every code file as `txt`, so the extension picks the
// glyph first and the kind is the fallback. Keys are lowercase extensions,
// or the whole lowercase name for dotless files (Dockerfile, LICENSE).
const EXTENSION_ICON: Record<string, FileIconName> = {
  '7z': 'zip',
  adoc: 'asciidoc',
  asciidoc: 'asciidoc',
  bash: 'bash',
  bat: 'batch',
  bin: 'binary',
  c: 'c',
  'c++': 'cpp',
  cc: 'cpp',
  cfg: 'properties',
  clj: 'clojure',
  cmake: 'cmake',
  cmd: 'batch',
  conf: 'properties',
  cpp: 'cpp',
  cs: 'csharp',
  css: 'css',
  csv: 'csv',
  cts: 'typescript',
  cxx: 'cpp',
  dart: 'dart',
  dat: 'binary',
  diff: 'diff',
  dll: 'exe',
  dockerfile: 'docker',
  env: 'env',
  envrc: 'env',
  erl: 'erlang',
  ex: 'elixir',
  exe: 'exe',
  exs: 'elixir',
  gitignore: 'git',
  go: 'go',
  gql: 'graphql',
  gradle: 'gradle',
  graphql: 'graphql',
  gz: 'zip',
  h: 'c-header',
  'h++': 'cpp-header',
  hh: 'cpp-header',
  hpp: 'cpp-header',
  hs: 'haskell',
  htm: 'html',
  html: 'html',
  http: 'http',
  hxx: 'cpp-header',
  ini: 'properties',
  ipynb: 'jupyter',
  java: 'java',
  jl: 'julia',
  js: 'javascript',
  jsx: 'javascript-react',
  kt: 'kotlin',
  kts: 'kotlin',
  latex: 'latex',
  less: 'less',
  lhs: 'haskell',
  license: 'license',
  lock: 'lock',
  log: 'log',
  lua: 'lua',
  makefile: 'makefile',
  mdx: 'markdown-mdx',
  mjs: 'javascript',
  mk: 'makefile',
  mkv: 'video',
  mov: 'video',
  mp4: 'video',
  mpeg: 'video',
  mts: 'typescript',
  org: 'org',
  otf: 'font',
  patch: 'diff',
  php: 'php',
  properties: 'properties',
  proto: 'proto',
  ps1: 'powershell',
  py: 'python',
  pyi: 'python',
  r: 'r',
  rar: 'zip',
  rb: 'ruby',
  readme: 'readme',
  rs: 'rust',
  sass: 'sass',
  scala: 'scala',
  scss: 'sass',
  sh: 'bash',
  sql: 'database',
  svelte: 'svelte',
  svg: 'svg',
  swift: 'swift',
  tar: 'zip',
  tex: 'latex',
  tgz: 'zip',
  toml: 'toml',
  ts: 'typescript',
  tsv: 'csv',
  tsx: 'typescript-react',
  ttf: 'font',
  typ: 'typst',
  vue: 'vue',
  webm: 'video',
  woff: 'font',
  woff2: 'font',
  xml: 'xml',
  xsd: 'xml',
  yaml: 'yaml',
  yml: 'yaml',
  zig: 'zig',
  zip: 'zip',
  zsh: 'bash',
};

const MATERIAL_ICON: Record<MaterialRefType, FileIconName> = {
  diagram: 'drawio',
  flashcards: 'java-enum',
  mindmap: 'forgejo',
  note: 'markdown',
  quiz: 'stackblitz',
};

export function fileIconName({
  kind,
  name,
}: Pick<SourceFile, 'kind' | 'name'>): FileIconName {
  const extension = name.slice(name.lastIndexOf('.') + 1).toLowerCase();
  return EXTENSION_ICON[extension] ?? KIND_ICON[kind];
}

export function materialIconName(type: MaterialRefType): FileIconName {
  return MATERIAL_ICON[type];
}
