import type { FileKind, MaterialRefType, SourceFile } from '@/api/types';

/** Symbol ids in src/assets/catppuccin.svg. */
export const FILE_ICON_NAMES = [
  '_folder',
  '_folder_open',
  '_file',
  'pdf',
  'ms-word',
  'markdown',
  'markdown-mdx',
  'image',
  'text',
  'ms-excel',
  'ms-powerpoint',
  'audio',
  'video',
  'json',
  'typescript',
  'typescript-react',
  'javascript',
  'javascript-react',
  'html',
  'css',
  'sass',
  'less',
  'vue',
  'svelte',
  'graphql',
  'python',
  'go',
  'rust',
  'java',
  'kotlin',
  'swift',
  'c',
  'c-header',
  'cpp',
  'cpp-header',
  'csharp',
  'ruby',
  'php',
  'dart',
  'scala',
  'lua',
  'r',
  'julia',
  'haskell',
  'elixir',
  'erlang',
  'clojure',
  'zig',
  'bash',
  'powershell',
  'batch',
  'database',
  'proto',
  'http',
  'yaml',
  'toml',
  'xml',
  'csv',
  'properties',
  'env',
  'lock',
  'jupyter',
  'asciidoc',
  'latex',
  'org',
  'typst',
  'log',
  'diff',
  'license',
  'readme',
  'docker',
  'makefile',
  'cmake',
  'gradle',
  'git',
  'zip',
  'exe',
  'font',
  'binary',
  'svg',
  'stackblitz',
  'java-enum',
  'vhs',
  'forgejo',
  'api-blueprint',
] as const;

export type FileIconName = (typeof FILE_ICON_NAMES)[number];

const KIND_ICON: Record<FileKind, FileIconName> = {
  audio: 'audio',
  doc: 'ms-word',
  image: 'image',
  json: 'json',
  md: 'markdown',
  pdf: 'pdf',
  sheet: 'ms-excel',
  slides: 'ms-powerpoint',
  txt: 'text',
  unknown: '_file',
};

// The backend files every code file as `txt`, so the extension picks the
// glyph first and the kind is the fallback. Keys are lowercase extensions,
// or the whole lowercase name for dotless files (Dockerfile, LICENSE).
const EXTENSION_ICON: Record<string, FileIconName> = {
  '7z': 'zip',
  aac: 'audio',
  adoc: 'asciidoc',
  asciidoc: 'asciidoc',
  bash: 'bash',
  bat: 'batch',
  bin: 'binary',
  bmp: 'image',
  c: 'c',
  'c++': 'cpp',
  cc: 'cpp',
  cfg: 'properties',
  clj: 'clojure',
  cmake: 'cmake',
  cmd: 'batch',
  conf: 'properties',
  cpp: 'cpp',
  cs: 'csharp',
  css: 'css',
  csv: 'csv',
  cts: 'typescript',
  cxx: 'cpp',
  dart: 'dart',
  dat: 'binary',
  diff: 'diff',
  dll: 'exe',
  doc: 'ms-word',
  dockerfile: 'docker',
  docx: 'ms-word',
  env: 'env',
  envrc: 'env',
  erl: 'erlang',
  ex: 'elixir',
  exe: 'exe',
  exs: 'elixir',
  flac: 'audio',
  gif: 'image',
  gitignore: 'git',
  go: 'go',
  gql: 'graphql',
  gradle: 'gradle',
  graphql: 'graphql',
  gz: 'zip',
  h: 'c-header',
  'h++': 'cpp-header',
  hh: 'cpp-header',
  hpp: 'cpp-header',
  hs: 'haskell',
  htm: 'html',
  html: 'html',
  http: 'http',
  hxx: 'cpp-header',
  ini: 'properties',
  ipynb: 'jupyter',
  java: 'java',
  jl: 'julia',
  jpeg: 'image',
  jpg: 'image',
  js: 'javascript',
  json: 'json',
  jsx: 'javascript-react',
  kt: 'kotlin',
  kts: 'kotlin',
  latex: 'latex',
  less: 'less',
  lhs: 'haskell',
  license: 'license',
  lock: 'lock',
  log: 'log',
  lua: 'lua',
  m4a: 'audio',
  makefile: 'makefile',
  markdown: 'markdown',
  md: 'markdown',
  mdx: 'markdown-mdx',
  mjs: 'javascript',
  mk: 'makefile',
  mkv: 'video',
  mov: 'video',
  mp3: 'audio',
  mp4: 'video',
  mpeg: 'video',
  mts: 'typescript',
  odp: 'ms-powerpoint',
  ods: 'ms-excel',
  odt: 'ms-word',
  ogg: 'audio',
  org: 'org',
  otf: 'font',
  patch: 'diff',
  pdf: 'pdf',
  php: 'php',
  png: 'image',
  ppt: 'ms-powerpoint',
  pptx: 'ms-powerpoint',
  properties: 'properties',
  proto: 'proto',
  ps1: 'powershell',
  py: 'python',
  pyi: 'python',
  r: 'r',
  rar: 'zip',
  rb: 'ruby',
  readme: 'readme',
  rs: 'rust',
  sass: 'sass',
  scala: 'scala',
  scss: 'sass',
  sh: 'bash',
  sql: 'database',
  svelte: 'svelte',
  svg: 'svg',
  swift: 'swift',
  tar: 'zip',
  tex: 'latex',
  tgz: 'zip',
  toml: 'toml',
  ts: 'typescript',
  tsv: 'csv',
  tsx: 'typescript-react',
  ttf: 'font',
  txt: 'text',
  typ: 'typst',
  vue: 'vue',
  wav: 'audio',
  webm: 'video',
  webp: 'image',
  woff: 'font',
  woff2: 'font',
  xls: 'ms-excel',
  xlsx: 'ms-excel',
  xml: 'xml',
  xsd: 'xml',
  yaml: 'yaml',
  yml: 'yaml',
  zig: 'zig',
  zip: 'zip',
  zsh: 'bash',
};

const MATERIAL_ICON: Record<MaterialRefType, FileIconName> = {
  diagram: 'api-blueprint',
  flashcards: 'vhs',
  mindmap: 'forgejo',
  note: 'java-enum',
  quiz: 'stackblitz',
};

export function fileIconName({
  kind,
  name,
}: Pick<SourceFile, 'kind' | 'name'>): FileIconName {
  const extension = name.slice(name.lastIndexOf('.') + 1).toLowerCase();
  return Object.hasOwn(EXTENSION_ICON, extension)
    ? EXTENSION_ICON[extension]
    : KIND_ICON[kind];
}

export function materialIconName(type: MaterialRefType): FileIconName {
  return MATERIAL_ICON[type];
}
