/**
 * i18n entry. Paraglide compiles `messages/*.json` into `src/i18n/paraglide`
 * (generated by the Vite plugin). Import all UI copy from here so there is a
 * single swappable surface.
 *
 * Usage:  import { m } from '@/i18n';  m.nav_dashboard()
 */

// @ts-expect-error generated at build time by the Paraglide Vite plugin
import { getLocale } from '@paraglide/runtime';
import { z } from 'zod';
import { en, zhCN } from 'zod/locales';

// @ts-expect-error generated at build time by the Paraglide Vite plugin
export * as m from '@paraglide/messages';
export {
  baseLocale,
  getLocale,
  locales,
  setLocale,
  // @ts-expect-error generated at build time by the Paraglide Vite plugin
} from '@paraglide/runtime';

export const LOCALE_LABELS: Record<string, string> = {
  en: 'English',
  zh: '中文',
};

// Zod's own messages (form and question validation) follow the UI locale.
z.config(getLocale() === 'zh' ? zhCN() : en());
