"""The shared agent-tool contract, generated by Go (`pnpm gen:openapi`).

``server/internal/agenttools`` owns tool definitions, resource operations and
result shapes. Python binds a local handler to a definition by name and
validates model arguments against the definition's JSON Schema before any
handler runs. An unknown contract version fails at import so an old service
never runs against a newer gateway.
"""

from __future__ import annotations

import json
from importlib import resources
from typing import Any

from jsonschema import Draft202012Validator, ValidationError

SUPPORTED_VERSION = 18


def _load() -> dict[str, Any]:
    raw = (
        resources.files("pipeline.generated")
        .joinpath("agent_tools.json")
        .read_text("utf-8")
    )
    contract = json.loads(raw)
    if contract.get("version") != SUPPORTED_VERSION:
        raise RuntimeError(
            f"agent tool contract version {contract.get('version')!r} is not "
            f"supported; this service understands {SUPPORTED_VERSION}"
        )
    return contract


CONTRACT = _load()
VERSION: int = CONTRACT["version"]
OPERATIONS: frozenset[str] = frozenset(CONTRACT["operations"])
OUTCOMES: frozenset[str] = frozenset(CONTRACT["outcomes"])
ERROR_CODES: frozenset[str] = frozenset(CONTRACT["errorCodes"])
DEFINITIONS: dict[str, dict[str, Any]] = {t["name"]: t for t in CONTRACT["tools"]}
# The note and question formats the materials skill quotes.
FORMATS: dict[str, str] = CONTRACT["formats"]

_validators: dict[str, Draft202012Validator] = {}
for _name, _definition in DEFINITIONS.items():
    if _definition.get("retention") not in (
        "full",
        "cited_passages",
        "used_excerpts",
        "none",
    ):
        raise RuntimeError(f"tool {_name} must declare conversation-result retention")
    Draft202012Validator.check_schema(_definition["inputSchema"])
    _validators[_name] = Draft202012Validator(_definition["inputSchema"])


def definition(name: str) -> dict[str, Any] | None:
    return DEFINITIONS.get(name)


def validate_args(name: str, args: dict[str, Any]) -> str | None:
    """Return the first schema violation as text, or None when valid."""
    validator = _validators.get(name)
    if validator is None:
        return f"No tool named {name}."
    error = next(iter(sorted(validator.iter_errors(args), key=str)), None)
    if error is None:
        return None
    where = "/".join(str(p) for p in error.absolute_path)
    return f"{name} arguments invalid at {where or '$'}: {_problem(error)}"


def _problem(error: ValidationError) -> str:
    """What is wrong, in a few words. The argument itself is never echoed: a
    command carrying a whole note section would come back at full size and
    hide the one field that is wrong."""
    if error.validator == "oneOf" and isinstance(error.instance, dict):
        tags = {
            v.get("properties", {}).get("type", {}).get("const"): v
            for v in error.validator_value
        }
        if None not in tags:
            return _variant_problem(tags, error.instance)
    if error.validator == "type":
        return f"must be {_types(error.validator_value)}"
    if error.validator in _BOUNDS:
        return f"{_BOUNDS[error.validator]} {error.validator_value}"
    text = error.message
    return text if len(text) <= 200 else text[:200] + " …"


_BOUNDS = {
    "minLength": "must have at least this many characters:",
    "maxLength": "must have at most this many characters:",
    "minItems": "must have at least this many items:",
    "maxItems": "must have at most this many items:",
    "minimum": "must be at least",
    "maximum": "must be at most",
}


def _types(value: Any) -> str:
    return " or ".join(value) if isinstance(value, list) else str(value)


def _variant_problem(tags: dict[str, dict[str, Any]], instance: dict[str, Any]) -> str:
    """A tagged-union member (an edit command): the tags when its type is not
    one of them, else the variant's fields it lacks, has extra or mistypes."""
    kind = instance.get("type")
    if kind not in tags:
        got = "" if kind is None else f", not {str(kind)[:40]!r}"
        return f'"type" must be one of {", ".join(tags)}{got}'
    variant = tags[kind]
    fields = variant["properties"]
    parts = [f"{kind} takes {', '.join(f for f in fields if f != 'type')}"]
    missing = [f for f in variant.get("required", []) if f not in instance]
    unknown = [f for f in instance if f not in fields]
    wrong = [
        f"{f} ({_problem(error)})"
        for f, value in instance.items()
        if f in fields
        for error in [next(Draft202012Validator(fields[f]).iter_errors(value), None)]
        if error is not None
    ]
    for label, names in (
        ("missing", missing),
        ("unknown", unknown),
        ("invalid", wrong),
    ):
        if names:
            parts.append(f"{label} {', '.join(names)}")
    return "; ".join(parts)


def model_schema(name: str) -> dict[str, Any]:
    """The model-facing function definition: name, description, arguments."""
    definition = DEFINITIONS[name]
    return {
        "type": "function",
        "function": {
            "name": definition["name"],
            "description": definition["description"],
            "parameters": definition["inputSchema"],
        },
    }
