"""The shared agent-tool contract, generated by Go (`pnpm gen:openapi`).

``server/internal/agenttools`` owns tool definitions, resource operations and
result shapes. Python binds a local handler to a definition by name and
validates model arguments against the definition's JSON Schema before any
handler runs. An unknown contract version fails at import so an old service
never runs against a newer gateway.
"""

from __future__ import annotations

import json
from importlib import resources
from typing import Any

from jsonschema import Draft202012Validator

SUPPORTED_VERSION = 1


def _load() -> dict[str, Any]:
    raw = (
        resources.files("pipeline.generated")
        .joinpath("agent_tools.json")
        .read_text("utf-8")
    )
    contract = json.loads(raw)
    if contract.get("version") != SUPPORTED_VERSION:
        raise RuntimeError(
            f"agent tool contract version {contract.get('version')!r} is not "
            f"supported; this service understands {SUPPORTED_VERSION}"
        )
    return contract


CONTRACT = _load()
VERSION: int = CONTRACT["version"]
OPERATIONS: frozenset[str] = frozenset(CONTRACT["operations"])
OUTCOMES: frozenset[str] = frozenset(CONTRACT["outcomes"])
ERROR_CODES: frozenset[str] = frozenset(CONTRACT["errorCodes"])
DEFINITIONS: dict[str, dict[str, Any]] = {t["name"]: t for t in CONTRACT["tools"]}

_validators: dict[str, Draft202012Validator] = {}
for _name, _definition in DEFINITIONS.items():
    Draft202012Validator.check_schema(_definition["inputSchema"])
    _validators[_name] = Draft202012Validator(_definition["inputSchema"])


def definition(name: str) -> dict[str, Any] | None:
    return DEFINITIONS.get(name)


def validate_args(name: str, args: dict[str, Any]) -> str | None:
    """Return the first schema violation as text, or None when valid."""
    validator = _validators.get(name)
    if validator is None:
        return f"No tool named {name}."
    error = next(iter(sorted(validator.iter_errors(args), key=str)), None)
    if error is None:
        return None
    where = "/".join(str(p) for p in error.absolute_path)
    return f"{name} arguments invalid at {where or '$'}: {error.message}"


def model_schema(name: str) -> dict[str, Any]:
    """The model-facing function definition: name, description, arguments."""
    definition = DEFINITIONS[name]
    return {
        "type": "function",
        "function": {
            "name": definition["name"],
            "description": definition["description"],
            "parameters": definition["inputSchema"],
        },
    }
