"""Office parity reports for DOCX, XLSX and PPTX.

Each checklist in ../fixtures/<format>.tsv gives a feature a hand-assigned status
per aspect (view, edit, save, collab) and the evidence for it. This script
resolves every evidence reference against the BetterOffice tree (the
vendor/betteroffice pin unless --fork names another checkout) and Capy, requires
a test behind every Y, and writes ../reports/PARITY-<FORMAT>.md.

    python3 bench/parity/scripts/parity.py              # regenerate the reports
    python3 bench/parity/scripts/parity.py --check      # validate only (CI)
    python3 bench/parity/scripts/parity.py --check --fork <fork worktree>

Any problem (a malformed row, a reference that does not resolve, a Y without a
test) is printed, nothing is written, and the exit code is 1.

Test names come from scanning the source, not from the runners: `cargo test --
--list` needs the workspace built, `bun test` cannot list, and vitest or
Playwright list modes need installed dependencies; the CI step has none of them.
Known gaps: tests generated by a Rust macro and TS tests whose title is not a
string literal (a variable or an expression) are not seen. Cite such a test by
its file alone or by a literal part of its title.
"""

import argparse
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

CAPY = Path(__file__).resolve().parents[3]
FAMILY = Path(__file__).resolve().parents[1]
FORMATS = ("docx", "xlsx", "pptx")
DIMS = ("view", "edit", "save", "collab")
COLUMNS = ["id", "area", "feature", "prio", *DIMS, "impact", "effort"]
COLUMNS += ["evidence", "notes", "todo"]
STATUSES = ("Y", "P", "N", "U", "-")
PRIO_WEIGHT = {"P0": 3, "P1": 2, "P2": 1}
EFFORTS = ("S", "M", "L", "XL")
VERIFIED = {"Y": 1.0, "P": 0.5, "U": 0.0, "N": 0.0}
CLAIMED = {"Y": 1.0, "P": 0.5, "U": 1.0, "N": 0.0}
TESTED = ("test", "matrix")
FORK_ROOTS = ("crates", "packages", "shared", "e2e")
CAPY_ROOTS = ("src", "e2e", "workers", "collaboration")
SKIP_DIRS = {"node_modules", "target", ".git", "dist", "generated", ".source"}

RUST_ATTR = re.compile(
    r"#\[(?:tokio::)?test\b|#\[(?:rstest|test_case|wasm_bindgen_test)\b"
)
RUST_FN = re.compile(r"\bfn\s+([$\w]+)")
TS_FILE = re.compile(
    r"\.(?:test|spec)\.[cm]?[jt]sx?$|\.matrix\.ts$"
    r"|/e2e/(?:docx|xlsx|pptx)/[^/]+\.ts$|/journeys/[^/]+\.ts$"
)
TITLE = r"""\s*\(\s*(['"`])((?:\\.|(?!\1)[^\\\n])*)\1"""
MODIFIER = r"\.(?:skip|only|fixme|todo|failing|concurrent|serial|each\((?:[^()\n]|\([^()\n]*\))*\))"
TS_TEST = re.compile(rf"(?:^|[^\w.$])(?:test|it)(?:{MODIFIER})*{TITLE}")
# The title after a multi-line test.each table: a line of closing brackets, then `)("title"`.
TS_EACH_TAIL = re.compile(
    rf"^\s*[\])][\])\s]*(?:as\s+const\s*\)\s*)?{TITLE}", re.MULTILINE
)


@dataclass
class Trees:
    capy: Path
    fork: Path
    capy_tests: dict
    fork_tests: dict


def rust_tests(text):
    """Names of #[test]-style functions; a macro-generated `fn $name` is skipped."""
    names, pending = [], False
    for line in text.splitlines():
        attr = RUST_ATTR.search(line)
        if attr:
            pending, line = True, line[attr.end() :]
        fn = pending and RUST_FN.search(line)
        if fn:
            pending = False
            if not fn.group(1).startswith("$"):
                names.append(fn.group(1))
    return names


def ts_tests(text):
    """Literal titles of test()/it() calls, including multi-line calls and test.each tables."""
    return [m.group(2) for p in (TS_TEST, TS_EACH_TAIL) for m in p.finditer(text)]


def scan(root, rel_roots):
    """{path relative to root: [test names]} for every file with at least one test."""
    found = {}
    for rel_root in rel_roots:
        for folder, dirs, files in os.walk(root / rel_root):
            dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
            for name in files:
                path = Path(folder, name)
                rel = path.relative_to(root).as_posix()
                if name.endswith(".rs"):
                    tests = rust_tests(path.read_text("utf-8", errors="replace"))
                elif TS_FILE.search("/" + rel):
                    tests = ts_tests(path.read_text("utf-8", errors="replace"))
                else:
                    continue
                if tests:
                    found[rel] = tests
    return found


def load_checklist(path):
    """(rows, problems); a row is a dict keyed by COLUMNS."""
    rows, problems, ids, header = [], [], set(), None
    for n, raw in enumerate(path.read_text("utf-8").splitlines(), 1):
        if not raw.strip() or raw.startswith("#"):
            continue
        cells = [c.strip() for c in raw.split("¦")]
        where = f"{path.name}:{n}"
        if header is None:
            header = cells
            if header != COLUMNS:
                return [], [f"{where}: header must be {' ¦ '.join(COLUMNS)}"]
            continue
        if len(cells) != len(COLUMNS):
            problems.append(f"{where}: {len(cells)} cells, expected {len(COLUMNS)}")
            continue
        row = dict(zip(COLUMNS, cells))
        bad = [f"{d} {row[d]!r}" for d in DIMS if row[d] not in STATUSES]
        if row["prio"] not in PRIO_WEIGHT:
            bad.append(f"prio {row['prio']!r}")
        if row["impact"] not in ("", "1", "2", "3", "4", "5"):
            bad.append(f"impact {row['impact']!r}")
        if row["effort"] not in ("", *EFFORTS):
            bad.append(f"effort {row['effort']!r}")
        if row["id"] in ids:
            bad.append("duplicate id")
        ids.add(row["id"])
        if bad:
            problems.append(f"{where} {row['id']}: invalid {', '.join(bad)}")
        rows.append(row)
    return rows, problems


def resolve(ref, trees):
    """(kind, ok, label) for one evidence reference."""
    kind, _, rest = ref.partition(":")
    if kind == "matrix":
        ok = (trees.fork / "shared/matrix/baseline" / f"{rest}.tsv").is_file()
        return "matrix", ok, f"matrix {rest}"
    if kind in ("fork", "capy"):
        path, _, needle = rest.partition("::")
        names = (trees.fork_tests if kind == "fork" else trees.capy_tests).get(path)
        label = (
            ("BO " if kind == "fork" else "")
            + path
            + (f" — {needle}" if needle else "")
        )
        if names is None:
            return "test", False, f"{label} (no tests in that file)"
        if needle and not any(needle.lower() in n.lower() for n in names):
            return "test", False, f"{label} (no such test)"
        return "test", True, label
    if kind == "code":
        repo, _, path = rest.partition(":")
        base = {"fork": trees.fork, "capy": trees.capy}.get(repo)
        label = f"code {'BO ' if repo == 'fork' else ''}{path}"
        return "code", base is not None and (base / path).exists(), label
    if kind == "doc":
        return "doc", (trees.capy / rest).exists(), f"doc {rest}"
    return "unknown", False, f"{ref} (unknown kind)"


def check(rows, trees):
    """Resolves each row's evidence into row['refs'] and returns the problems."""
    problems = []
    for row in rows:
        refs = []
        for item in filter(None, (x.strip() for x in row["evidence"].split(" ; "))):
            dim, sep, ref = item.partition("@")
            if not (sep and dim in DIMS):
                dim, ref = None, item
            kind, ok, label = resolve(ref, trees)
            refs.append((dim, kind, ok, label))
            if not ok:
                problems.append(f"{row['id']}: unresolved {label}")
        for d in DIMS:
            tested = any(ok and k in TESTED and s in (None, d) for s, k, ok, _ in refs)
            if row[d] == "Y" and not tested:
                problems.append(f"{row['id']}: {d} is Y without a test")
        row["refs"] = refs
    return problems


def read_fidelity(path):
    """(measured commit, {format: table rows}) from the benchmark's section.md."""
    text = path.read_text("utf-8")
    commit = re.search(r"/commit/([0-9a-f]{40})", text)
    tables = {}
    for fmt, body in re.findall(
        r"^### (DOCX|PPTX|XLSX)\n(.*?)(?=^### |\Z)", text, re.MULTILINE | re.DOTALL
    ):
        rows = []
        for tr in re.findall(r"<tr>(.*?)</tr>", body, re.DOTALL):
            cells = re.findall(r"<t[hd][^>]*>(.*?)</t[hd]>", tr, re.DOTALL)
            rows.append([re.sub(r"<[^>]+>", "", c).strip() for c in cells])
        if rows:
            tables[fmt.lower()] = rows
    if not commit or set(tables) != set(FORMATS):
        return None, {}
    return commit.group(1), tables


def matrix_facts(fork):
    """(generator, rows, {class: count}) per DOCX matrix baseline."""
    out = []
    for path in sorted((fork / "shared/matrix/baseline").glob("*.tsv")):
        lines = path.read_text("utf-8").splitlines()
        total = int(re.match(r"# \S+: (\d+) rows", lines[0]).group(1))
        classes = {}
        for line in lines[1:]:
            cls = line.rsplit("\t", 1)[-1].split("+")[0]
            classes[cls] = classes.get(cls, 0) + 1
        classes["exact"] = classes.get("exact", 0) + total - (len(lines) - 1)
        out.append((path.stem, total, classes))
    return out


def test_counts(fmt, trees):
    in_path = re.compile(rf"(^|[/_-]){fmt}([/_.-]|$)", re.IGNORECASE)
    in_title = re.compile(rf"\b{fmt}\b", re.IGNORECASE)
    fork = sum(len(v) for k, v in trees.fork_tests.items() if in_path.search(k))
    capy = sum(
        1
        for k, names in trees.capy_tests.items()
        for n in names
        if in_path.search(k) or in_title.search(n)
    )
    return fork, capy


def parity(rows, values):
    """Weighted parity in percent and per-priority means."""
    num = den = 0.0
    by_prio = {}
    for row in rows:
        scores = [values[row[d]] for d in DIMS if row[d] in values]
        if not scores:
            continue
        score = sum(scores) / len(scores)
        num += PRIO_WEIGHT[row["prio"]] * score
        den += PRIO_WEIGHT[row["prio"]]
        by_prio.setdefault(row["prio"], []).append(score)
    return 100 * num / den, {
        p: (100 * sum(s) / len(s), len(s)) for p, s in by_prio.items()
    }


def cell(text):
    return text.replace("|", "\\|")


def render(fmt, rows, trees, pin, fidelity):
    upper = fmt.upper()
    out = [
        f"# {upper} parity",
        "",
        (
            f"Generated by `bench/parity/scripts/parity.py` from `bench/parity/fixtures/{fmt}.tsv` "
            f"against BetterOffice `{pin}`; edit the checklist, not this file. Statuses are "
            "hand-assigned (reference: Google Docs, Sheets and Slides; Office for view and save "
            "fidelity); the script checks that every cited test, file and matrix exists on that tree "
            "and that every Y cites a test."
        ),
        "",
        (
            "Legend: **Y** works and a test shows it; **P** partial (see notes); **N** missing; "
            "**U** believed to work, no test yet (unverified); – not applicable. View = opens and "
            "displays like Office; Edit = a Capy user can do it in the editor; Save = survives "
            "editing and export (round trip); Collab = two people at once converge, with a two-peer "
            "test. Priority: P0 = a student or teacher hits it in their first week, P1 = common, "
            "P2 = occasional. Effort (one agent incl. tests and review): S ≤ 1 day, M 2–5 days, "
            "L 1–3 weeks, XL more."
        ),
        "",
        "## Summary",
        "",
        "| Aspect | " + " | ".join(s.replace("-", "–") for s in STATUSES) + " |",
        "|---|---|---|---|---|---|",
    ]
    for d in DIMS:
        counts = [sum(row[d] == s for row in rows) for s in STATUSES]
        out.append(f"| {d} | " + " | ".join(map(str, counts)) + " |")
    out.append("")
    for label, values, u in (("verified", VERIFIED, 0), ("claimed", CLAIMED, 1)):
        total, by_prio = parity(rows, values)
        prios = ", ".join(
            f"{p} {v:.0f}% ({n} rows)" for p, (v, n) in sorted(by_prio.items())
        )
        out.append(
            f"- Weighted parity, {label}: **{total:.0f}%** ({prios}). A row scores the mean of "
            f"its aspects (Y 1, P 0.5, N 0, U {u}); rows weigh P0 3, P1 2, P2 1."
        )
    fork_n, capy_n = test_counts(fmt, trees)
    refs = sum(len(row["refs"]) for row in rows)
    out.append(
        f"- {len(rows)} features, {refs} evidence references, all resolving. Tests naming "
        f"{fmt} in their path or title: {fork_n} in the fork, {capy_n} in Capy."
    )
    if fmt == "docx":
        for name, total, classes in matrix_facts(trees.fork):
            split = ", ".join(
                f"{k} {v}" for k, v in sorted(classes.items(), key=lambda kv: -kv[1])
            )
            out.append(f"- Matrix `{name}`: {total} rows ({split}).")
    out += ["", "## Fidelity against Office", ""]
    commit, tables = fidelity
    if commit is None:
        out.append(
            "No benchmark result yet. The fork's Benchmarks workflow (`visual-fidelity.yml`, "
            "upstream's real-file corpus) runs on every push to capy-ci; copy its "
            "`visual-fidelity` artifact's `section.md` to `bench/parity/fixtures/fidelity.md` "
            "and regenerate."
        )
    else:
        on_pin = commit.startswith(pin)
        where = "the pin" if on_pin else f"not the pin `{pin}`"
        out += [
            (
                f"From the fork's Benchmarks workflow on BetterOffice `{commit[:8]}` ({where}): "
                "render similarity and page counts against Office's own renders of upstream's "
                "real-file corpus, next to upstream's latest release and LibreOffice "
                "(`bench/parity/fixtures/fidelity.md`)."
            ),
            "",
        ]
        head, *body = tables[fmt]
        out.append("| " + " | ".join(head) + " |")
        out.append("|" + "---|" * len(head))
        out += ["| " + " | ".join(r) + " |" for r in body]
    area = None
    out += ["", "## Features"]
    for row in rows:
        if row["area"] != area:
            area = row["area"]
            out += ["", f"### {area}", ""]
            out.append(
                "| ID | Feature | Prio | View | Edit | Save | Collab | Evidence | Notes |"
            )
            out.append("|---|---|---|---|---|---|---|---|---|")
        evidence = "<br>".join(
            (f"[{s}] " if s else "") + label for s, _, _, label in row["refs"]
        )
        statuses = " | ".join(
            {"N": "**N**", "-": "–"}.get(row[d], row[d]) for d in DIMS
        )
        out.append(
            f"| {row['id']} | {cell(row['feature'])} | {row['prio']} | {statuses} | "
            f"{cell(evidence) or '—'} | {cell(row['notes'])} |"
        )
    out += [
        "",
        "## Remaining work, ranked by user impact",
        "",
        "Rows with any N or P, by priority, then impact (5 = hit first or most often), then effort.",
        "",
    ]
    effort = {e: i for i, e in enumerate(EFFORTS)}
    open_rows = [row for row in rows if any(row[d] in ("N", "P") for d in DIMS)]
    open_rows.sort(
        key=lambda r: (
            r["prio"],
            -int(r["impact"] or 0),
            effort.get(r["effort"], len(EFFORTS)),
        )
    )
    for i, row in enumerate(open_rows, 1):
        gaps = ", ".join(f"{d} {row[d]}" for d in DIMS if row[d] in ("N", "P", "U"))
        out.append(
            f"{i}. **{row['feature']}** ({row['id']}; {row['prio']}, impact "
            f"{row['impact'] or '?'}, effort {row['effort'] or '?'}; {gaps}). "
            f"{row['todo'] or row['notes']}"
        )
    out += [
        "",
        "## Verification debt (tests to add)",
        "",
        "Aspects believed to work but shown by no test (U), by priority.",
        "",
    ]
    for row in sorted(rows, key=lambda r: (r["prio"], r["id"])):
        dims = ", ".join(d for d in DIMS if row[d] == "U")
        if dims:
            out.append(f"- {row['prio']} **{row['feature']}** ({row['id']}): {dims}.")
    return "\n".join(out) + "\n"


def git_head(path):
    result = subprocess.run(
        ["git", "-C", str(path), "rev-parse", "--short=8", "HEAD"],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode:
        sys.exit(
            f"cannot read the BetterOffice commit at {path}: {result.stderr.strip()}"
        )
    return result.stdout.strip()


def run(capy, fork, family, check_only):
    if not (fork / "crates").is_dir():
        print(
            f"{fork} is not a BetterOffice checkout (git submodule update --init vendor/betteroffice)"
        )
        return 1
    trees = Trees(capy, fork, scan(capy, CAPY_ROOTS), scan(fork, FORK_ROOTS))
    problems, checklists = [], {}
    fidelity = (None, {})
    fidelity_path = family / "fixtures" / "fidelity.md"
    if fidelity_path.exists():
        fidelity = read_fidelity(fidelity_path)
        if fidelity[0] is None:
            problems.append(
                "fidelity.md: not a Benchmarks section.md (commit link and three tables)"
            )
    for fmt in FORMATS:
        rows, found = load_checklist(family / "fixtures" / f"{fmt}.tsv")
        problems += found + check(rows, trees)
        checklists[fmt] = rows
    for problem in problems:
        print(problem)
    if problems:
        return 1
    pin = None if check_only else git_head(fork)
    for fmt, rows in checklists.items():
        if pin:
            report = family / "reports" / f"PARITY-{fmt.upper()}.md"
            report.write_text(
                render(fmt, rows, trees, pin, fidelity), "utf-8", newline="\n"
            )
        print(
            f"{fmt}: {len(rows)} features, {sum(len(r['refs']) for r in rows)} references, ok"
        )
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--check", action="store_true", help="validate only, write nothing"
    )
    parser.add_argument("--fork", type=Path, default=CAPY / "vendor" / "betteroffice")
    args = parser.parse_args()
    sys.stdout.reconfigure(encoding="utf-8")
    return run(CAPY, args.fork.resolve(), FAMILY, args.check)


if __name__ == "__main__":
    sys.exit(main())
