import type { IconSet } from '@betteroffice/docx-react';
import {
  AlignBottomIcon,
  AlignTopIcon,
  AlignVerticalCenterIcon,
  ArrowHorizontalIcon,
  ArrowLeft02Icon,
  ArrowVerticalIcon,
  BorderAllIcon,
  BorderBottomIcon,
  BorderFullIcon,
  BorderHorizontalIcon,
  BorderInnerIcon,
  BorderLeftIcon,
  BorderNoneIcon,
  BorderRightIcon,
  BorderTopIcon,
  BorderVerticalIcon,
  BringToFrontIcon,
  BubbleChatDoneIcon,
  Cancel01Icon,
  CheckIcon,
  CheckmarkCircle02Icon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClipboardPasteIcon,
  ColumnInsertIcon,
  CombineIcon,
  Comment01Icon,
  CommentAdd01Icon,
  Copy01Icon,
  Delete02Icon,
  DeleteColumnIcon,
  DeleteRowIcon,
  Download01Icon,
  DropletOffIcon,
  ExpandIcon,
  FlipHorizontalIcon,
  FlipVerticalIcon,
  GeometricShapes01Icon,
  Globe02Icon,
  Grid3X3Icon,
  GripVerticalIcon,
  HighlighterIcon,
  Image01Icon,
  InsertColumnLeftIcon,
  InsertColumnRightIcon,
  InsertRowDownIcon,
  InsertRowUpIcon,
  LayerSendToBackIcon,
  LayoutTableIcon,
  LeftToRightListBulletIcon,
  LeftToRightListNumberIcon,
  LineStyleIcon,
  Link04Icon,
  ListIndentDecreaseIcon,
  ListIndentIncreaseIcon,
  Menu01Icon,
  MinusSignIcon,
  MoreVerticalIcon,
  MoveIcon,
  PaintBrush01Icon,
  PaintBucketIcon,
  PencilEdit01Icon,
  PlusSignIcon,
  PrinterIcon,
  Redo03Icon,
  RotateLeft01Icon,
  RotateRight01Icon,
  RowDeleteIcon,
  RowInsertIcon,
  ScissorIcon,
  ScissorsLineDashedIcon,
  Settings01Icon,
  SlidersHorizontalIcon,
  SparklesIcon,
  Stamp01Icon,
  TableIcon,
  TableOfContentsIcon,
  TextAlignCenterIcon,
  TextAlignJustifyIcon,
  TextAlignLeftIcon,
  TextAlignRightIcon,
  TextBoldIcon,
  TextClearIcon,
  TextColorIcon,
  TextFontIcon,
  TextIcon,
  TextItalicIcon,
  TextSelectionIcon,
  TextStrikethroughIcon,
  TextSubscriptIcon,
  TextSuperscriptIcon,
  TextUnderlineIcon,
  TextWrapIcon,
  TickDouble01Icon,
  Undo03Icon,
  UngroupIcon,
  Unlink04Icon,
  Upload01Icon,
} from '@hugeicons/core-free-icons';
import type { IconSvgElement } from '@hugeicons/react';
import type { ComponentProps } from 'react';
import { HugeIcon } from '@/components/ui/HugeIcon';

// Capy's own icons where Hugeicons has none, as in Icon.tsx.
const PILCROW = ['M10 3v11', 'M14 3v11', 'M16 3H9.5a3.5 3.5 0 000 7H10'];

/**
 * Every icon docx-react draws, from Capy's set: the same icon as Icon.tsx for
 * the same command. Imported one by one so the rest of Hugeicons stays out of
 * the runtime bundle.
 */
const ICONS: Record<keyof IconSet, IconSvgElement | readonly string[]> = {
  add: PlusSignIcon,
  add_comment: CommentAdd01Icon,
  'agent-sparkle': SparklesIcon,
  arrow_back: ArrowLeft02Icon,
  arrow_drop_down: ChevronDownIcon,
  border_all: BorderAllIcon,
  border_bottom: BorderBottomIcon,
  border_clear: BorderNoneIcon,
  border_color: PencilEdit01Icon,
  border_horizontal: BorderHorizontalIcon,
  border_inner: BorderInnerIcon,
  border_left: BorderLeftIcon,
  border_outer: BorderFullIcon,
  border_right: BorderRightIcon,
  border_top: BorderTopIcon,
  border_vertical: BorderVerticalIcon,
  branding_watermark: Stamp01Icon,
  call_merge: CombineIcon,
  call_split: UngroupIcon,
  chat_bubble_check: BubbleChatDoneIcon,
  chat_bubble_outline: Comment01Icon,
  check: CheckIcon,
  check_circle: CheckmarkCircle02Icon,
  close: Cancel01Icon,
  comment: Comment01Icon,
  delete: Delete02Icon,
  delete_sweep: RowDeleteIcon,
  done_all: TickDouble01Icon,
  drag_indicator: GripVerticalIcon,
  expand_less: ChevronUpIcon,
  expand_more: ChevronDownIcon,
  file_download: Download01Icon,
  file_upload: Upload01Icon,
  fit_width: ArrowHorizontalIcon,
  flip_to_back: LayerSendToBackIcon,
  flip_to_front: BringToFrontIcon,
  format_align_center: TextAlignCenterIcon,
  format_align_justify: TextAlignJustifyIcon,
  format_align_left: TextAlignLeftIcon,
  format_align_right: TextAlignRightIcon,
  format_bold: TextBoldIcon,
  format_clear: TextClearIcon,
  format_color_fill: PaintBucketIcon,
  format_color_reset: DropletOffIcon,
  format_color_text: TextColorIcon,
  format_image_left: [
    'M3 5h8v8H3z',
    'M14 6h7',
    'M14 10h7',
    'M3 17h18',
    'M3 21h18',
  ],
  format_image_right: [
    'M13 5h8v8h-8z',
    'M3 6h7',
    'M3 10h7',
    'M3 17h18',
    'M3 21h18',
  ],
  format_indent_decrease: ListIndentDecreaseIcon,
  format_indent_increase: ListIndentIncreaseIcon,
  format_italic: TextItalicIcon,
  format_line_spacing: [
    'M11 6h9',
    'M11 12h9',
    'M11 18h9',
    'M6 5v14',
    'M3.5 7.5 6 5l2.5 2.5',
    'M3.5 16.5 6 19l2.5-2.5',
  ],
  format_list_bulleted: LeftToRightListBulletIcon,
  format_list_numbered: LeftToRightListNumberIcon,
  format_paint: PaintBrush01Icon,
  format_textdirection_l_to_r: [...PILCROW, 'M5 19h14', 'M16 16l3 3-3 3'],
  format_textdirection_r_to_l: [...PILCROW, 'M19 19H5', 'M8 16l-3 3 3 3'],
  format_underlined: TextUnderlineIcon,
  grid_on: TableIcon,
  height: ArrowVerticalIcon,
  horizontal_rule: ['M4 12h16'],
  image: Image01Icon,
  ink_highlighter: HighlighterIcon,
  keyboard_arrow_down: ChevronDownIcon,
  keyboard_arrow_left: ChevronLeftIcon,
  keyboard_arrow_right: ChevronRightIcon,
  keyboard_arrow_up: ChevronUpIcon,
  line_weight: LineStyleIcon,
  link: Link04Icon,
  'link-copy': Copy01Icon,
  'link-edit': PencilEdit01Icon,
  'link-open': Globe02Icon,
  'link-remove': Unlink04Icon,
  'link-text': TextFontIcon,
  'link-url': Link04Icon,
  menu: Menu01Icon,
  'menu-column-delete': DeleteColumnIcon,
  'menu-column-left': InsertColumnLeftIcon,
  'menu-column-right': InsertColumnRightIcon,
  'menu-comment': CommentAdd01Icon,
  'menu-copy': Copy01Icon,
  'menu-cut': ScissorIcon,
  'menu-delete': Delete02Icon,
  'menu-delete-table': Delete02Icon,
  'menu-merge-cells': CombineIcon,
  'menu-paste': ClipboardPasteIcon,
  'menu-row-above': InsertRowUpIcon,
  'menu-row-below': InsertRowDownIcon,
  'menu-row-delete': DeleteRowIcon,
  'menu-select-all': TextSelectionIcon,
  'menu-select-table': Grid3X3Icon,
  'menu-split-cell': UngroupIcon,
  more_vert: MoreVerticalIcon,
  open_with: MoveIcon,
  padding: ExpandIcon,
  page_break: ScissorsLineDashedIcon,
  print: PrinterIcon,
  redo: Redo03Icon,
  remove: MinusSignIcon,
  rotate_left: RotateLeft01Icon,
  rotate_right: RotateRight01Icon,
  select_all: Grid3X3Icon,
  settings: Settings01Icon,
  shapes: GeometricShapes01Icon,
  strikethrough_s: TextStrikethroughIcon,
  subscript: TextSubscriptIcon,
  superscript: TextSuperscriptIcon,
  swap_horiz: FlipHorizontalIcon,
  swap_vert: FlipVerticalIcon,
  table: TableIcon,
  table_chart: LayoutTableIcon,
  table_rows: RowInsertIcon,
  'table-insert': PlusSignIcon,
  text_rotation_none: TextIcon,
  toc: TableOfContentsIcon,
  tune: SlidersHorizontalIcon,
  undo: Undo03Icon,
  vertical_align_bottom: AlignBottomIcon,
  vertical_align_center: AlignVerticalCenterIcon,
  vertical_align_top: AlignTopIcon,
  view_column: ColumnInsertIcon,
  wrap_text: TextWrapIcon,
};

/** Capy's toolbars and menus draw 16px icons; smaller requests stay smaller. */
export const docxIcons = Object.fromEntries(
  Object.entries(ICONS).map(([name, icon]) => [
    name,
    ({
      size = 16,
      className,
      style,
    }: ComponentProps<IconSet[keyof IconSet]>) => (
      <HugeIcon
        className={className}
        icon={icon}
        size={Math.min(size, 16)}
        style={style}
      />
    ),
  ])
) as IconSet;
