// Code generated by scripts/build-emails.ts. DO NOT EDIT.
// Source of truth: messages/*.json. Run `pnpm email:build` to regenerate.

package mail

// subjectTemplates holds subject lines keyed by "<template>.<locale>". They
// are Go text/template sources and share the body templates' data.
var subjectTemplates = map[string]string{
	"workspace-invite.en":         "You're invited to join {{.WorkspaceName}} on Evo Notes",
	"workspace-invite.zh":         "邀请你加入 Evo Notes 工作区 {{.WorkspaceName}}",
	"workspace-member-removed.en": "You were removed from {{.WorkspaceName}}",
	"workspace-member-removed.zh": "你已被移出 {{.WorkspaceName}}",
	"workspace-role-changed.en":   "Your role changed in {{.WorkspaceName}}",
	"workspace-role-changed.zh":   "你在 {{.WorkspaceName}} 中的角色已更改",
}

// roleLabels holds workspace role names keyed by "<role>.<locale>".
var roleLabels = map[string]string{
	"commenter.en": "Commenter",
	"commenter.zh": "评论者",
	"editor.en":    "Editor",
	"editor.zh":    "编辑者",
	"viewer.en":    "Viewer",
	"viewer.zh":    "查看者",
}
