// Code generated by scripts/build-emails.ts. DO NOT EDIT.
// Source of truth: emails/templates/*.json. Run `pnpm email:build` to regenerate.

package mail

// subjectTemplates holds subject lines keyed by "<template>.<locale>". They
// are Go text/template sources and share the body templates' data.
var subjectTemplates = map[string]string{
	"account-deletion-cancelled.en": "Your Capy Notebook account deletion was cancelled",
	"account-deletion-cancelled.zh": "你的 Capy Notebook 账户删除已取消",
	"account-deletion-requested.en": "Your Capy Notebook account deletion is scheduled",
	"account-deletion-requested.zh": "你的 Capy Notebook 账户删除已安排",
	"subscription-frozen.en":        "Your Capy Notebook account is frozen",
	"subscription-frozen.zh":        "你的 Capy Notebook 账户已被冻结",
	"subscription-over-quota.en":    "Your Capy Notebook storage is over the free limit",
	"subscription-over-quota.zh":    "你的 Capy Notebook 存储已超过免费额度",
	"workspace-invite.en":           "You're invited to join {{.WorkspaceName}} on Capy Notebook",
	"workspace-invite.zh":           "邀请你加入 Capy Notebook 工作区 {{.WorkspaceName}}",
}
