/**
 * Renders locale-specific Maily JSON into Go templates that the API embeds, so
 * production never needs Node. Subject and body placeholders remain Go
 * template actions and are filled when the API sends a message.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { compile } from '@inlang/paraglide-js';
import { Maily } from '@maily-to/render';
import type { JSONContent } from '@tiptap/core';
import {
  type EmailLocale,
  emailLocales,
  emailRendererTheme,
  emailTemplateDefinitions,
  emailTemplateSourceSchema,
  validateTemplateVariables,
} from '../emails/schema';

const projectRoot = process.cwd();
const paraglideOutDir = join(projectRoot, 'src', 'i18n', 'paraglide');
const sourceDir = join(projectRoot, 'emails', 'templates');
const mailDir = join(projectRoot, 'server', 'internal', 'mail');
const templateDir = join(mailDir, 'templates');
const TRAILING_WHITESPACE_PATTERN = /[ \t]+$/gm;

// Workspace roles remain application messages because they also appear outside
// email templates. Compile the catalog before importing the generated module.
await compile({
  outdir: paraglideOutDir,
  project: join(projectRoot, 'project.inlang'),
});

const { m } = await import('../src/i18n/paraglide/messages.js');

async function readSource(templateId: string, locale: EmailLocale) {
  const file = join(sourceDir, `${templateId}.${locale}.json`);
  const raw = await readFile(file, 'utf8');
  return emailTemplateSourceSchema.parse(JSON.parse(raw));
}

async function renderSource(
  templateId: string,
  locale: EmailLocale,
  source: Awaited<ReturnType<typeof readSource>>
) {
  const definition = emailTemplateDefinitions.find(
    (candidate) => candidate.id === templateId
  );
  if (!definition) throw new Error(`unknown email template ${templateId}`);
  validateTemplateVariables(definition, source);

  const renderer = new Maily(source.content as JSONContent);
  renderer.setHtmlProps({ dir: 'ltr', lang: locale });
  renderer.setPreviewText(source.preview);
  renderer.setTheme(emailRendererTheme);
  renderer.setVariableFormatter(({ variable }) => `{{.${variable}}}`);

  return {
    html: (await renderer.render())
      .replace(TRAILING_WHITESPACE_PATTERN, '')
      .trim(),
    text: (await renderer.render({ plainText: true }))
      .replace(TRAILING_WHITESPACE_PATTERN, '')
      .trim(),
  };
}

const roleLabels: Record<string, (locale: EmailLocale) => string> = {
  commenter: (locale) => m.notification_role_commenter({}, { locale }),
  editor: (locale) => m.notification_role_editor({}, { locale }),
  viewer: (locale) => m.notification_role_viewer({}, { locale }),
};

function goMap(name: string, doc: string, entries: Map<string, string>) {
  const rows = [...entries]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, value]) => [`${JSON.stringify(key)}:`, value] as const);
  // gofmt aligns map values into a column; emit it pre-aligned so the output is
  // stable without shelling out to Go.
  const width = Math.max(...rows.map(([label]) => label.length));
  const lines = rows
    .map(([label, value]) => {
      const padding = ' '.repeat(width - label.length + 1);
      return `\t${label}${padding}${JSON.stringify(value)},`;
    })
    .join('\n');
  return `${doc}\nvar ${name} = map[string]string{\n${lines}\n}\n`;
}

const subjects = new Map<string, string>();
const roles = new Map<string, string>();

await mkdir(templateDir, { recursive: true });
for (const locale of emailLocales) {
  for (const definition of emailTemplateDefinitions) {
    const key = `${definition.id}.${locale}`;
    const source = await readSource(definition.id, locale);
    const rendered = await renderSource(definition.id, locale, source);

    subjects.set(key, source.subject);
    await writeFile(join(templateDir, `${key}.gohtml`), `${rendered.html}\n`);
    await writeFile(join(templateDir, `${key}.txt`), `${rendered.text}\n`);
  }
  for (const [role, label] of Object.entries(roleLabels)) {
    roles.set(`${role}.${locale}`, label(locale));
  }
}

const generatedGo = [
  '// Code generated by scripts/build-emails.ts. DO NOT EDIT.',
  '// Source of truth: emails/templates/*.json. Run `pnpm email:build` to regenerate.',
  '',
  'package mail',
  '',
  goMap(
    'subjectTemplates',
    '// subjectTemplates holds subject lines keyed by "<template>.<locale>". They\n// are Go text/template sources and share the body templates\' data.',
    subjects
  ),
  goMap(
    'roleLabels',
    '// roleLabels holds workspace role names keyed by "<role>.<locale>".',
    roles
  ),
].join('\n');

await writeFile(join(mailDir, 'copy_gen.go'), generatedGo);
