/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Capy Notebook API
 * OpenAPI spec version: 0.1.0
 */

export type Slot = (typeof Slot)[keyof typeof Slot];

export const Slot = {
  captioning: 'captioning',
  chat: 'chat',
  editor: 'editor',
  generate: 'generate',
  ingest: 'ingest',
  quiz: 'quiz',
  retrieval: 'retrieval',
} as const;
