/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Capy Notebook API
 * OpenAPI spec version: 0.1.0
 */

export type Slot = typeof Slot[keyof typeof Slot];


export const Slot = {
  chat: 'chat',
  generate: 'generate',
  editor: 'editor',
  quiz: 'quiz',
  ingest: 'ingest',
  retrieval: 'retrieval',
  captioning: 'captioning',
} as const;
