/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Evo Notes API
 * OpenAPI spec version: 0.1.0
 */

export type Surface = (typeof Surface)[keyof typeof Surface];

export const Surface = {
  chat: 'chat',
  editor: 'editor',
  embedding: 'embedding',
  generate: 'generate',
  ingest: 'ingest',
  quiz: 'quiz',
  vision: 'vision',
} as const;
