import {
  Alert02Icon,
  Archive01Icon,
  ArrowDown02Icon,
  ArrowExpand01Icon,
  ArrowLeft02Icon,
  ArrowLeft04Icon,
  ArrowRight02Icon,
  ArrowRight04Icon,
  ArrowShrink02Icon,
  ArrowUp02Icon,
  AtIcon,
  BellIcon,
  Book02Icon,
  BookCheckIcon,
  BookEditIcon,
  BookOpen01Icon,
  BookOpenCheckIcon,
  BracesIcon,
  Calendar04Icon,
  Cancel01Icon,
  CancelCircleIcon,
  ChartColumnBigIcon,
  ChartLineData01Icon,
  CheckIcon,
  CheckListIcon,
  CheckmarkCircle02Icon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleDashedIcon,
  CircleIcon,
  ClipboardPasteIcon,
  Clock01Icon,
  ClosedCaptionIcon,
  CloudAlertIcon,
  CloudIcon,
  CloudOffIcon,
  CloudSavingDone01Icon,
  CloudUploadIcon,
  CombineIcon,
  Comment01Icon,
  CommentAdd01Icon,
  Copy01Icon,
  Copy02Icon,
  Crown03Icon,
  Cursor01Icon,
  DashboardSquare01Icon,
  DatabaseIcon,
  Delete02Icon,
  Download01Icon,
  Edit04Icon,
  Eraser01Icon,
  ExternalLinkIcon,
  FeatherIcon,
  File02Icon,
  FileAudioIcon,
  FileEditIcon,
  FileEmpty02Icon,
  FileExclamationPointIcon,
  FilePlusIcon,
  FilterVerticalIcon,
  FlashIcon,
  Flowchart01Icon,
  GeometricShapes01Icon,
  Globe02Icon,
  Grid3X3Icon,
  GripHorizontalIcon,
  GripVerticalIcon,
  Heading01Icon,
  Heading02Icon,
  Heading03Icon,
  Heading04Icon,
  Heading05Icon,
  Heading06Icon,
  HelpCircleIcon,
  HighlighterIcon,
  Image01Icon,
  InformationCircleIcon,
  Key01Icon,
  KeyboardIcon,
  LayoutThreeColumnIcon,
  LayoutTwoColumnIcon,
  LeftToRightListBulletIcon,
  LeftToRightListNumberIcon,
  Link04Icon,
  ListChevronsDownUpIcon,
  ListIndentDecreaseIcon,
  ListIndentIncreaseIcon,
  ListPlusIcon,
  ListXIcon,
  Loading03Icon,
  Location01Icon,
  LogoutSquare01Icon,
  MagicWand01Icon,
  Menu01Icon,
  Message01Icon,
  MessageAdd01Icon,
  Mic01Icon,
  MinusSignIcon,
  Moon02Icon,
  MoreVerticalIcon,
  PaintBucketIcon,
  PanelLeftIcon,
  PanelRightIcon,
  ParagraphIcon,
  PartyPopperIcon,
  PencilEdit01Icon,
  PencilEdit02Icon,
  PlusSignCircleIcon,
  PlusSignIcon,
  Presentation01Icon,
  PrinterIcon,
  QuoteDownIcon,
  Redo03Icon,
  RefreshCcwIcon,
  ScissorIcon,
  Search01Icon,
  SearchAddIcon,
  SearchMinusIcon,
  SecurityWarningIcon,
  SendHorizontalIcon,
  Settings01Icon,
  Settings02Icon,
  SourceCodeIcon,
  SparklesIcon,
  SquareIcon,
  SquareLock02Icon,
  StopIcon,
  Summation01Icon,
  Sun03Icon,
  TableIcon,
  TableOfContentsIcon,
  Task01Icon,
  TextAlignCenterIcon,
  TextAlignJustifyIcon,
  TextAlignLeftIcon,
  TextAlignRightIcon,
  TextBoldIcon,
  TextColorIcon,
  TextFontIcon,
  TextItalicIcon,
  TextStrikethroughIcon,
  TextSubscriptIcon,
  TextSuperscriptIcon,
  TextUnderlineIcon,
  Undo03Icon,
  UngroupIcon,
  Unlink04Icon,
  Upload01Icon,
  User02Icon,
  ViewIcon,
  ViewOffIcon,
  WifiError02Icon,
  WifiOff02Icon,
} from '@hugeicons/core-free-icons';
import type { CSSProperties } from 'react';
import { HugeIcon } from './HugeIcon';

const HugeIcons = {
  alert: Alert02Icon,
  alignCenter: TextAlignCenterIcon,
  alignJustify: TextAlignJustifyIcon,
  alignLeft: TextAlignLeftIcon,
  alignRight: TextAlignRightIcon,
  archive: Archive01Icon,
  arrowDown: ArrowDown02Icon,
  arrowLeft: ArrowLeft02Icon,
  arrowRight: ArrowRight02Icon,
  arrowUp: ArrowUp02Icon,
  at: AtIcon,
  bell: BellIcon,
  bold: TextBoldIcon,
  book: BookOpen01Icon,
  bookCheck: BookCheckIcon,
  bookEdit: BookEditIcon,
  bookOpenCheck: BookOpenCheckIcon,
  braces: BracesIcon,
  CloudIcon,
  chapter: Archive01Icon,
  chart: ChartColumnBigIcon,
  check: CheckIcon,
  chevronDown: ChevronDownIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  chevronUp: ChevronUpIcon,
  circleCheck: CheckmarkCircle02Icon,
  circleDashed: CircleDashedIcon,
  circleX: CancelCircleIcon,
  clipboard: Task01Icon,
  clipboardPaste: ClipboardPasteIcon,
  clock: Clock01Icon,
  clone: Copy02Icon,
  closedCaption: ClosedCaptionIcon,
  cloudAlert: CloudAlertIcon,
  cloudOff: CloudOffIcon,
  cloudSavingDone: CloudSavingDone01Icon,
  cloudSync: CloudUploadIcon,
  code: SourceCodeIcon,
  columns2: LayoutTwoColumnIcon,
  columns3: LayoutThreeColumnIcon,
  combine: CombineIcon,
  comment: Comment01Icon,
  commentAdd: CommentAdd01Icon,
  copy: Copy01Icon,
  cursor: Cursor01Icon,
  dashboard: DashboardSquare01Icon,
  database: DatabaseIcon,
  diagram: Flowchart01Icon,
  download: Download01Icon,
  ellipse: CircleIcon,
  eraser: Eraser01Icon,
  error: Alert02Icon,
  externalLink: ExternalLinkIcon,
  feather: FeatherIcon,
  fileAudio: FileAudioIcon,
  fileError: FileExclamationPointIcon,
  filePlus: FilePlusIcon,
  files: FileEmpty02Icon,
  fileText: File02Icon,
  filter: FilterVerticalIcon,
  flashcards: [
    'M5 7h11a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2V9a2 2 0 012-2z',
    'M8 4h11a2 2 0 012 2v8',
  ],
  folderCollapse: ListChevronsDownUpIcon,
  globe: Globe02Icon,
  graph: ChartLineData01Icon,
  grid: Grid3X3Icon,
  gripHorizontal: GripHorizontalIcon,
  gripVertical: GripVerticalIcon,
  heading1: Heading01Icon,
  heading2: Heading02Icon,
  heading3: Heading03Icon,
  heading4: Heading04Icon,
  heading5: Heading05Icon,
  heading6: Heading06Icon,
  help: HelpCircleIcon,
  highlighter: HighlighterIcon,
  image: Image01Icon,
  indentDecrease: ListIndentDecreaseIcon,
  indentIncrease: ListIndentIncreaseIcon,
  info: InformationCircleIcon,
  italic: TextItalicIcon,
  key: Key01Icon,
  keyboard: KeyboardIcon,
  link: Link04Icon,
  list: LeftToRightListBulletIcon,
  listMinus: ListXIcon,
  listOrdered: LeftToRightListNumberIcon,
  listPlus: ListPlusIcon,
  loader: Loading03Icon,
  location: Location01Icon,
  lock: SquareLock02Icon,
  logout: LogoutSquare01Icon,
  maximize: ArrowExpand01Icon,
  menu: Menu01Icon,
  message: Message01Icon,
  microphone: Mic01Icon,
  minimize: ArrowShrink02Icon,
  minus: MinusSignIcon,
  moon: Moon02Icon,
  moreVertical: MoreVerticalIcon,
  navigationBack: ArrowLeft04Icon,
  navigationForward: ArrowRight04Icon,
  newChat: MessageAdd01Icon,
  newFile: FileEditIcon,
  newNote: PencilEdit02Icon,
  paintBucket: PaintBucketIcon,
  palette: [
    'M12 3.5a8.5 8.5 0 00-.5 17c1 0 1.5-.8 1.5-1.6 0-1.2-1-1.6-1-2.6 0-.8.7-1.3 1.5-1.3H15a5 5 0 005-5C20 6.5 16.4 3.5 12 3.5z',
    'M7.5 12.5h.01',
    'M9.5 8.5h.01',
    'M14 8h.01',
  ],
  panelLeft: PanelLeftIcon,
  panelRight: PanelRightIcon,
  paragraph: ParagraphIcon,
  partyPopper: PartyPopperIcon,
  pencil: PencilEdit01Icon,
  plus: PlusSignIcon,
  plusCircle: PlusSignCircleIcon,
  preferences: Settings02Icon,
  premium: Crown03Icon,
  presentation: Presentation01Icon,
  print: PrinterIcon,
  profile: User02Icon,
  quiz: FlashIcon,
  quote: QuoteDownIcon,
  rectangle: SquareIcon,
  redo: Redo03Icon,
  refresh: RefreshCcwIcon,
  removeFromChapter: Eraser01Icon,
  schedule: Calendar04Icon,
  scissors: ScissorIcon,
  search: Search01Icon,
  securityWarning: SecurityWarningIcon,
  send: SendHorizontalIcon,
  settings: Settings01Icon,
  shape: GeometricShapes01Icon,
  sigma: Summation01Icon,
  sparkles: SparklesIcon,
  stop: StopIcon,
  strikethrough: TextStrikethroughIcon,
  subscript: TextSubscriptIcon,
  sun: Sun03Icon,
  superscript: TextSuperscriptIcon,
  table: TableIcon,
  tableOfContents: TableOfContentsIcon,
  text: TextFontIcon,
  textColor: TextColorIcon,
  todo: CheckListIcon,
  trash: Delete02Icon,
  underline: TextUnderlineIcon,
  undo: Undo03Icon,
  ungroup: UngroupIcon,
  unlink: Unlink04Icon,
  upload: Upload01Icon,
  view: ViewIcon,
  viewOff: ViewOffIcon,
  wand: MagicWand01Icon,
  wifiError: WifiError02Icon,
  wifiOff: WifiOff02Icon,
  workspaces: Book02Icon,
  write: Edit04Icon,
  x: Cancel01Icon,
  zoomIn: SearchAddIcon,
  zoomOut: SearchMinusIcon,
} as const;

export type IconName = keyof typeof HugeIcons;

/** For names that arrive as data, such as the Office runtime's menus. */
export function isIconName(name: string): name is IconName {
  return Object.hasOwn(HugeIcons, name);
}

export type IconProps = React.ComponentProps<'svg'> & {
  className?: string;
  name: IconName;
  size?: number;
  strokeWidth?: number;
  style?: CSSProperties;
};

export function Icon({ name, ...rest }: IconProps) {
  return <HugeIcon icon={HugeIcons[name] ?? HugeIcons.x} {...rest} />;
}
